export type Statue = {
  author: string | null;
  category: string | null;
  code: number;
  created_at: string | null;
  description: string | null;
  district: string | null;
  house_number: string | null;
  id: number;
  lat: number;
  lng: number;
  material: string | null;
  name: string | null;
  street: string | null;
  street_number: string | null;
  style: string | null;
  type: string | null;
  url_3d: string | null;
  url_catalog: string | null;
  url_wiki: string | null;
  year: string | null;
  img1: string | undefined;
};
