

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


CREATE EXTENSION IF NOT EXISTS "pg_cron" WITH SCHEMA "pg_catalog";






CREATE EXTENSION IF NOT EXISTS "pg_net" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgsodium";






COMMENT ON SCHEMA "public" IS 'standard public schema';



CREATE EXTENSION IF NOT EXISTS "pg_graphql" WITH SCHEMA "graphql";






CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgjwt" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";






CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";






CREATE OR REPLACE FUNCTION "public"."handle_new_user"() RETURNS "trigger"
    LANGUAGE "plpgsql" SECURITY DEFINER
    AS $$
begin
  insert into public.profiles (id, full_name, avatar_url)
  values (new.id, new.raw_user_meta_data->>'full_name', new.raw_user_meta_data->>'avatar_url');
  return new;
end;
$$;


ALTER FUNCTION "public"."handle_new_user"() OWNER TO "postgres";

SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."deleted_users" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "message" "text",
    "email" "text",
    "user_id" "uuid"
);


ALTER TABLE "public"."deleted_users" OWNER TO "postgres";


ALTER TABLE "public"."deleted_users" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."deleted_users_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."profile_follows" (
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "follower_id" "uuid" NOT NULL,
    "following_id" "uuid" NOT NULL
);


ALTER TABLE "public"."profile_follows" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."profile_statue_collected" (
    "profile_id" "uuid" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "statue_id" bigint NOT NULL,
    "value" smallint NOT NULL
);


ALTER TABLE "public"."profile_statue_collected" OWNER TO "postgres";


COMMENT ON TABLE "public"."profile_statue_collected" IS 'Collected statues by profiles';



COMMENT ON COLUMN "public"."profile_statue_collected"."value" IS 'Statue value at collection time';



CREATE TABLE IF NOT EXISTS "public"."profiles" (
    "id" "uuid" NOT NULL,
    "updated_at" timestamp with time zone,
    "username" "text",
    "full_name" "text",
    "avatar_url" "text",
    "website" "text",
    "dev_mode" boolean DEFAULT false NOT NULL,
    CONSTRAINT "username_length" CHECK (("char_length"("username") >= 3))
);


ALTER TABLE "public"."profiles" OWNER TO "postgres";


COMMENT ON COLUMN "public"."profiles"."dev_mode" IS 'Feature flag enabling some dev features';



CREATE TABLE IF NOT EXISTS "public"."statue_scores" (
    "id" bigint NOT NULL,
    "created_at" "date" NOT NULL,
    "statue_id" bigint,
    "score" smallint
);


ALTER TABLE "public"."statue_scores" OWNER TO "postgres";


ALTER TABLE "public"."statue_scores" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."statue_score_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."statues" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "name" "text" NOT NULL,
    "lng" double precision NOT NULL,
    "lat" double precision NOT NULL,
    "visible" boolean NOT NULL,
    "description" "text",
    "material" "text",
    "type" "text",
    "category" "text",
    "author" "text",
    "year" "text",
    "place" "text",
    "wiki_url" "text",
    "image_url" "text"
);


ALTER TABLE "public"."statues" OWNER TO "postgres";


ALTER TABLE "public"."statues" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."statues_id_seq1"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."user_feedbacks" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "profile_id" "uuid",
    "statue_id" bigint,
    "message" "text"
);


ALTER TABLE "public"."user_feedbacks" OWNER TO "postgres";


ALTER TABLE "public"."user_feedbacks" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."user_feedbacks_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



ALTER TABLE ONLY "public"."deleted_users"
    ADD CONSTRAINT "deleted_users_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."profile_follows"
    ADD CONSTRAINT "profile_follows_pkey" PRIMARY KEY ("follower_id", "following_id");



ALTER TABLE ONLY "public"."profile_statue_collected"
    ADD CONSTRAINT "profile_statue_collected_pkey" PRIMARY KEY ("profile_id", "statue_id");



ALTER TABLE ONLY "public"."profiles"
    ADD CONSTRAINT "profiles_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."profiles"
    ADD CONSTRAINT "profiles_username_key" UNIQUE ("username");



ALTER TABLE ONLY "public"."statue_scores"
    ADD CONSTRAINT "statue_score_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."statues"
    ADD CONSTRAINT "statues_pkey1" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."user_feedbacks"
    ADD CONSTRAINT "user_feedbacks_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."profile_follows"
    ADD CONSTRAINT "profile_follows_follower_id_fkey" FOREIGN KEY ("follower_id") REFERENCES "public"."profiles"("id");



ALTER TABLE ONLY "public"."profile_follows"
    ADD CONSTRAINT "profile_follows_following_id_fkey" FOREIGN KEY ("following_id") REFERENCES "public"."profiles"("id");



ALTER TABLE ONLY "public"."profile_statue_collected"
    ADD CONSTRAINT "profile_statue_collected_statue_id_fkey" FOREIGN KEY ("statue_id") REFERENCES "public"."statues"("id");



ALTER TABLE ONLY "public"."profiles"
    ADD CONSTRAINT "profiles_id_fkey" FOREIGN KEY ("id") REFERENCES "auth"."users"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."profile_statue_collected"
    ADD CONSTRAINT "public_profile_statue_collected_profile_id_fkey" FOREIGN KEY ("profile_id") REFERENCES "public"."profiles"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."statue_scores"
    ADD CONSTRAINT "statue_score_statue_id_fkey" FOREIGN KEY ("statue_id") REFERENCES "public"."statues"("id");



ALTER TABLE ONLY "public"."user_feedbacks"
    ADD CONSTRAINT "user_feedbacks_statue_id_fkey" FOREIGN KEY ("statue_id") REFERENCES "public"."statues"("id");



ALTER TABLE ONLY "public"."user_feedbacks"
    ADD CONSTRAINT "user_feedbacks_uuid_fkey" FOREIGN KEY ("profile_id") REFERENCES "public"."profiles"("id");



CREATE POLICY "Public profiles are viewable by everyone." ON "public"."profiles" FOR SELECT USING (true);



CREATE POLICY "Users can insert their own profile." ON "public"."profiles" FOR INSERT WITH CHECK ((( SELECT "auth"."uid"() AS "uid") = "id"));



CREATE POLICY "Users can update own profile." ON "public"."profiles" FOR UPDATE USING ((( SELECT "auth"."uid"() AS "uid") = "id"));



ALTER TABLE "public"."deleted_users" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."profile_follows" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."profile_statue_collected" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."profiles" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."statue_scores" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."statues" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."user_feedbacks" ENABLE ROW LEVEL SECURITY;




ALTER PUBLICATION "supabase_realtime" OWNER TO "postgres";








GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";









































































































































































































GRANT ALL ON FUNCTION "public"."handle_new_user"() TO "anon";
GRANT ALL ON FUNCTION "public"."handle_new_user"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."handle_new_user"() TO "service_role";
























GRANT ALL ON TABLE "public"."deleted_users" TO "anon";
GRANT ALL ON TABLE "public"."deleted_users" TO "authenticated";
GRANT ALL ON TABLE "public"."deleted_users" TO "service_role";



GRANT ALL ON SEQUENCE "public"."deleted_users_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."deleted_users_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."deleted_users_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."profile_follows" TO "anon";
GRANT ALL ON TABLE "public"."profile_follows" TO "authenticated";
GRANT ALL ON TABLE "public"."profile_follows" TO "service_role";



GRANT ALL ON TABLE "public"."profile_statue_collected" TO "anon";
GRANT ALL ON TABLE "public"."profile_statue_collected" TO "authenticated";
GRANT ALL ON TABLE "public"."profile_statue_collected" TO "service_role";



GRANT ALL ON TABLE "public"."profiles" TO "anon";
GRANT ALL ON TABLE "public"."profiles" TO "authenticated";
GRANT ALL ON TABLE "public"."profiles" TO "service_role";



GRANT ALL ON TABLE "public"."statue_scores" TO "anon";
GRANT ALL ON TABLE "public"."statue_scores" TO "authenticated";
GRANT ALL ON TABLE "public"."statue_scores" TO "service_role";



GRANT ALL ON SEQUENCE "public"."statue_score_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."statue_score_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."statue_score_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."statues" TO "anon";
GRANT ALL ON TABLE "public"."statues" TO "authenticated";
GRANT ALL ON TABLE "public"."statues" TO "service_role";



GRANT ALL ON SEQUENCE "public"."statues_id_seq1" TO "anon";
GRANT ALL ON SEQUENCE "public"."statues_id_seq1" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."statues_id_seq1" TO "service_role";



GRANT ALL ON TABLE "public"."user_feedbacks" TO "anon";
GRANT ALL ON TABLE "public"."user_feedbacks" TO "authenticated";
GRANT ALL ON TABLE "public"."user_feedbacks" TO "service_role";



GRANT ALL ON SEQUENCE "public"."user_feedbacks_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."user_feedbacks_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."user_feedbacks_id_seq" TO "service_role";



ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "service_role";






























CREATE TRIGGER on_auth_user_created AFTER INSERT ON auth.users FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();


  create policy "Anyone can upload an avatar."
  on "storage"."objects"
  as permissive
  for insert
  to public
with check ((bucket_id = 'avatars'::text));



  create policy "Avatar images are publicly accessible."
  on "storage"."objects"
  as permissive
  for select
  to public
using ((bucket_id = 'avatars'::text));



